# Generated by Django 6.0 on 2026-01-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("piro_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="질문 내용")),
                (
                    "answered",
                    models.BooleanField(default=False, verbose_name="답변 완료"),
                ),
                ("reply", models.TextField(blank=True, null=True, verbose_name="답변")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="questions/",
                        verbose_name="첨부 이미지",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="piro_sessions.session",
                        verbose_name="세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "질문",
                "verbose_name_plural": "질문 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
