# Generated by Django 6.0 on 2026-01-06 09:38

import utils.file_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.file_upload.safe_file_upload_path,
                verbose_name="첨부 이미지",
            ),
        ),
    ]
