# Generated by Django 6.0 on 2026-01-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("piro_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("link", "링크"),
                            ("file", "파일"),
                            ("image", "이미지"),
                            ("text", "텍스트"),
                        ],
                        max_length=10,
                        verbose_name="타입",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="제목"),
                ),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contents/",
                        verbose_name="파일",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="piro_sessions.session",
                        verbose_name="세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "콘텐츠",
                "verbose_name_plural": "콘텐츠 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200, verbose_name="진도 내용")),
                ("order", models.IntegerField(default=0, verbose_name="순서")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_boxes",
                        to="piro_sessions.session",
                        verbose_name="세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "진도 박스",
                "verbose_name_plural": "진도 박스 목록",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, verbose_name="사용자 ID")),
                (
                    "emotion",
                    models.CharField(
                        choices=[("happy", "😊"), ("sad", "😢")],
                        max_length=10,
                        verbose_name="감정",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "progress_box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="piro_contents.progressbox",
                        verbose_name="진도 박스",
                    ),
                ),
            ],
            options={
                "verbose_name": "진도 체크",
                "verbose_name_plural": "진도 체크 목록",
                "unique_together": {("progress_box", "user_id")},
            },
        ),
    ]
