# Generated by Django 6.0 on 2026-01-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='세션 제목')),
                ('date', models.DateField(verbose_name='세션 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '세션',
                'verbose_name_plural': '세션 목록',
                'ordering': ['date'],
            },
        ),
    ]
