# Generated by Django 6.0 on 2026-01-06 09:38

import utils.file_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=utils.file_upload.safe_file_upload_path,
                verbose_name="파일",
            ),
        ),
    ]
